name: pizzabiere
services:
  pgdb:
    image: postgres
    restart: always
    env_file: ./.env
    environment:
      - DATABASE_HOST=$DB_HOST
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    networks:
      - default

  pgdbadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - pgdb

  # nestjs-app:
  #   container_name: blankapi
  #   depends_on:
  #     - postgres
  #   build: ./blankapi
  #   restart: unless-stopped
  #   env_file: ./.env
  #   ports:
  #     - $NESTJS_APP_LOCAL_PORT:$NESTJS_APP_DOCKER_PORT
  #   environment:
  #     - DB_HOST=$DB_HOST
  #     - DB_USER=$DB_USER
  #     - DB_PASSWORD=$DB_PASSWORD
  #     - DB_DATABASE=$DB_DATABASE
  #     - DB_PORT=$DB_DOCKER_PORT
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./nestjs-app:/app
  #     - /app/node_modules
  #   networks:
  #     - default

  # nextjs-app:
  #   container_name: nextjs-app
  #   depends_on:
  #     - nestjs-app
  #   build:
  #     context: ./nextjs-app
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   env_file: ./.env
  #   ports:
  #     - $NEXTJS_APP_LOCAL_PORT:$NEXTJS_APP_DOCKER_PORT
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./nextjs-app:/app
  #     - /app/node_modules
  #     - /app/.next
  #   networks:
  #     - default
